package pro.crypto.model;

public enum IndicatorType {

    SIMPLE_MOVING_AVERAGE,
    EXPONENTIAL_MOVING_AVERAGE,
    WEIGHTED_MOVING_AVERAGE,
    SMOOTHED_MOVING_AVERAGE,
    HULL_MOVING_AVERAGE,
    DISPLACED_MOVING_AVERAGE,
    MODIFIED_MOVING_AVERAGE,
    MOVING_AVERAGE_CONVERGENCE_DIVERGENCE,
    COMMODITY_CHANNEL_INDEX,
    ACCUMULATION_DISTRIBUTION_LINE,
    ON_BALANCE_VOLUME,
    CHAIKIN_OSCILLATOR,
    CHAIKIN_MONEY_FLOW,
    ULTIMATE_OSCILLATOR,
    STANDARD_DEVIATION,
    AVERAGE_TRUE_RANGE,
    KELTNER_CHANNEL,
    RELATIVE_STRENGTH_INDEX,
    CONNORS_RELATIVE_STRENGTH_INDEX,
    STOCHASTIC_RELATIVE_STRENGTH_INDEX,
    STOCHASTIC_OSCILLATOR,
    PREFERABLE_STOCHASTIC_OSCILLATOR,
    MOVING_AVERAGE_ENVELOPES,
    AVERAGE_DIRECTIONAL_MOVEMENT_INDEX,
    BOLLINGER_BANDS,
    BOLLINGER_BANDS_WIDTH,
    WILLIAMS_PERCENT_RANGE,
    AROON_UP_DOWN,
    ELDERS_FORCE_INDEX,
    RANGE_OF_CHANGE,
    TRIPLE_EXPONENTIAL_MOVING_AVERAGE

}
