package pro.crypto.model;

public enum IndicatorType {

    SIMPLE_MOVING_AVERAGE,
    EXPONENTIAL_MOVING_AVERAGE,
    WEIGHTED_MOVING_AVERAGE,
    SMOOTHED_MOVING_AVERAGE,
    HULL_MOVING_AVERAGE,
    DISPLACED_MOVING_AVERAGE,
    MOVING_AVERAGE_CONVERGENCE_DIVERGENCE,
    COMMODITY_CHANNEL_INDEX,
    ACCUMULATION_DISTRIBUTION_LINE,
    ON_BALANCE_VOLUME,
    CHAIKIN_OSCILLATOR,
    CHAIKIN_MONEY_FLOW,
    ULTIMATE_OSCILLATOR,
    STANDARD_DEVIATION,
    AVERAGE_TRUE_RANGE,
    KELTNER_CHANNEL,
    RELATIVE_STRENGTH_INDEX

}
