package pro.crypto;

public enum SettingKey {

    NOTIFICATIONS_EMAIL_LOGIN,
    NOTIFICATIONS_EMAIL_PASSWORD,
    NOTIFICATIONS_EMAIL_SMTP_HOST,
    NOTIFICATIONS_EMAIL_SMTP_PORT,
    NOTIFICATIONS_EMAIL_REQUIRE_SECURE_CONNECTION,
    NOTIFICATIONS_EMAIL_OUTCOMING,
    NOTIFICATION_SMS_API_VERSION,
    NOTIFICATIONS_SMS_API_KEY,
    NOTIFICATIONS_SMS_COMMAND,
    NOTIFICATIONS_SMS_FROM

}
