package pro.crypto;

public enum SettingKey {

    NOTIFICATIONS_EMAIL_LOGIN,
    NOTIFICATIONS_EMAIL_PASSWORD,
    NOTIFICATIONS_EMAIL_SMTP_HOST,
    NOTIFICATIONS_EMAIL_SMTP_PORT,
    NOTIFICATIONS_EMAIL_REQUIRE_SECURE_CONNECTION,
    NOTIFICATIONS_EMAIL_OUTCOMING

}
